from typing import Dict, List
from google.cloud import bigquery

TABLE_SCHEMAS: Dict[str, List[bigquery.SchemaField]] = {
    'event': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_campaign_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('splash_theme_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('splash_theme_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('title', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description_text', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_first_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_last_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_start', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('event_end', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('hide_event_time', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('venue_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('address', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('city', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('state', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('zip_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('country', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('created_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modified_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('domain', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('custom_domain', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('paid_for_domain', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('published', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('hub', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fq_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('mobile_check_in_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_attendance_types', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('group_ids', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('registration_updating_enabled', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('registration_updating_deadline', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_setting': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('header_image', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_open', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('wait_list', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_method', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('lat', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('lng', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('event_hashtag', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('venue_tbd', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_guest_display', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_state', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_team_notified', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('page_privacy_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_host', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('button_closed_message', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('autosave', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_stats': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('count', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_ticket_type': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_triggered_email': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('trigger', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('subject', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('content', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('include_calendar_attachment', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('include_pdf_attachment', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('include_invoice_pdf', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('pdf_content', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('use_default_confirmation', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('active', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_message_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_message_linked_to_theme', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_type': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('code_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('splash_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('public_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('is_enterprise_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_order': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('currency_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('currency_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('currency_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('order_number', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('status', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('placed', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('total', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('foreign_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('foreign_total', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_discount_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('flat_discount', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('percent_discount', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('discount_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('tax', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('stripe_fee', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fees_owed', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fees_paid', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fee_refunded', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('amount_refunded', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('cardholder_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_order_discount': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('flat_discount', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('percent_discount', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_sale': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('unit_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('total_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('is_refunded', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity_sold', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('sold_out', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('order_min', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('order_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fee_paid_by_buyer', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('sort', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('collect_rsvp_fields', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('non_dollar', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('expires_length', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('nested_ticket', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('show_remaining', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('open_price', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('open_price_min', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('open_price_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('add_guest_name', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type_custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type_discount': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_discount_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'group_contact': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_campaign_member_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_rsvp_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('first_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('last_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('status', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modified', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'group_contact_answer': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('group_contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('answer', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'group_contact_email_campaign_status': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('group_contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('email_campaign_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('status', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'group_contact_event_rsvp': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('group_contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('attending', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('date_rsvped', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('checked_in', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('checked_out', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('plus_one', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modified', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_sale_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_number', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('vip', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('waitlist', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('qr_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('unsub_tag', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('unsubscribed', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'contact': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_object_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('first_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('last_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('title', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('primary_email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('organization_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('phone', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('unsubscribed', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('createdate', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modifydate', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('vip', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('bounced', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('bounced_event', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('bounced_on', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('bounced_reason', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('invalid_email', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('source_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('object_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('object_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('values', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('selected_values', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('external_link', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('protected', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'splash_theme': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('abbr', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('image_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('thumbnail_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('sort', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
}
