from typing import Dict, List
from google.cloud import bigquery

TABLE_SCHEMAS: Dict[str, List[bigquery.SchemaField]] = {
    'event': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_campaign_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('splash_theme_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('splash_theme_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('title', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description_text', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_first_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_last_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_owner_email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_start', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('event_end', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('hide_event_time', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('venue_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('address', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('city', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('state', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('zip_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('country', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('created_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modified_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('domain', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('custom_domain', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('paid_for_domain', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('published', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('hub', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fq_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('mobile_check_in_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_attendance_types', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('group_ids', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('registration_updating_enabled', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('registration_updating_deadline', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_setting': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('header_image', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_open', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('wait_list', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_method', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('lat', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('lng', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('event_hashtag', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('venue_tbd', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_guest_display', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_state', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_at', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('rsvp_closed_team_notified', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('page_privacy_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_host', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('button_closed_message', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('autosave', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_stats': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('count', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_ticket_type': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_triggered_email': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('event_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_setting_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('trigger', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('subject', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('content', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('include_calendar_attachment', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('include_pdf_attachment', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('include_invoice_pdf', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('pdf_content', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('use_default_confirmation', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('active', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_message_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('event_message_linked_to_theme', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'event_type': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('code_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('splash_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('public_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('is_enterprise_type', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
}
