from typing import Dict, List
from google.cloud import bigquery

TABLE_SCHEMAS: Dict[str, List[bigquery.SchemaField]] = {
    'contact': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('salesforce_object_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('first_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('last_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('title', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('primary_email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('organization_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('phone', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('unsubscribed', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('createdate', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('modifydate', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('vip', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('bounced', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('bounced_event', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('bounced_on', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('bounced_reason', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('invalid_email', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('source_id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('object_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('object_type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('values', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('selected_values', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('deleted', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('external_link', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('protected', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'splash_theme': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('abbr', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('image_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('thumbnail_url', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('sort', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
}
