from typing import Dict, List
from google.cloud import bigquery

TABLE_SCHEMAS: Dict[str, List[bigquery.SchemaField]] = {
    'ticket_order': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('contact_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('currency_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('currency_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('currency_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('order_number', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('status', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('created', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('placed', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('total', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('foreign_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('foreign_total', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_discount_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('flat_discount', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('percent_discount', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('discount_code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('tax', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('stripe_fee', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fees_owed', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fees_paid', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fee_refunded', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('amount_refunded', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('email', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('cardholder_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_order_discount': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('flat_discount', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('percent_discount', 'FLOAT', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('code', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_sale': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('unit_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('total_price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('is_refunded', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type': [
        bigquery.SchemaField('id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('description', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('price', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('quantity_sold', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('sold_out', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('active', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('order_min', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('order_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('fee_paid_by_buyer', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('sort', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('collect_rsvp_fields', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('non_dollar', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('expires_length', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('nested_ticket', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('show_remaining', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('open_price', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('open_price_min', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('open_price_max', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('add_guest_name', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type_custom_question': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('custom_question_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('type', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('column_name', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('required', 'BOOLEAN', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
    'ticket_type_discount': [
        bigquery.SchemaField('id', 'STRING', mode='NULLABLE'),
        bigquery.SchemaField('ticket_type_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('ticket_order_discount_id', 'INTEGER', mode='NULLABLE'),
        bigquery.SchemaField('_sync_time', 'TIMESTAMP', mode='NULLABLE'),
        bigquery.SchemaField('_deleted', 'BOOLEAN', mode='NULLABLE'),
    ],
}
